name: Install Python Dependencies
description: "Installs Python dependencies for the project."
inputs:
  python-version:
    required: true
    description: "The Python version to install dependencies for."
  gh-token:
    required: true
    description: "The GitHub token to use for authentication."

runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pipenv
    - name: Install System Dependencies
      shell: bash
      run: |
        pipx install pipenv
        pip install multivenv
    - name: Print out system info
      shell: bash
      run: mvenv info -i json
    - name: Install Just command runner
      uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
    - id: get-requirements-path
      shell: bash
      run: |
        reqs_extension=$(python reqs_extension.py)
        global_reqs_file=$(python reqs_path.py global)
        echo "::set-output name=requirements-extension::$reqs_extension"
        echo "::set-output name=global-requirements-path::$global_reqs_file"
    - uses: actions/cache@v3
      name: Cache global dependencies
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles(steps.get-requirements-path.outputs.global-requirements-path) }}
    - uses: actions/cache@v3
      id: cache-venvs
      name: Cache venvs
      with:
        path: venvs
        key: ${{ env.pythonLocation }}-venvs-${{ hashFiles(format('requirements/*-requirements-{0}.txt', steps.get-requirements-path.outputs.requirements-extension)) }}
    - name: Install main dependencies
      shell: bash
      run: |
        pipenv --python ${{ matrix.python-version }} sync
    - name: Create venvs
      shell: bash
      if: steps.cache-venvs.outputs.cache-hit != 'true'
      run: |
        mvenv sync
