branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

repositoryUrl: https://github.com/nickderobertis/pypi-sphinx-flexlate-example

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "semantic-release-pypi"
  - "@semantic-release/github"