name: Lint and Test
description: "Runs Flake8, mypy, pytest. Be sure to run install-dependencies first"
runs:
  using: composite
  steps:
    - name: Lint with flake8
      shell: bash
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Static Typing Checks with mypy
      shell: bash
      run: |
        pipenv run mypy $(python directory.py)
    - name: Test with pytest
      shell: bash
      run: |
        pipenv run python -m pytest --cov=./ --cov-report=xml
