
name: Build and Push Docs

on:
  push:
    paths:
      - "docsrc/**"
      - "README.md"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/lint-and-test
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-pytest
          yml: ./codecov.yml

  deploy:
    needs: test

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/build-and-deploy-docs
        with:
          gh-token: ${{ secrets.GH_TOKEN }}