name: Test, Build and Push Python Package and Docs

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - "*.*.*"
      - "*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/lint-and-test

  collectTODO:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.3"
        id: "todo"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            semantic-release-pypi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  coverage:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run coverage and upload to Codecov.io
        uses: ./.github/actions/test-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}